name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Deploy to GitHub Pages
      run: |
        mkdir -p ./public
        cp -r ./*.html ./public/
        cp -r ./assets ./public/ || true
        echo 'Deploying HTML files...'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
